### ISSUE TITLE
Using Proftpd in swarm mode ?

### ISSUE THREAD

**Issue by osfrance** [AndrewVos/docker-proftpd#6]
Hi,
I try to use ProFTPd in a Docker Swarm mode, but when I try to connect my ftp client try swarm IP :
> Statut :	Résolution de l'adresse de srv1.test.org
> Statut :	Connexion à 192.168.1.1:21...
> Statut :	Connexion établie, attente du message d'accueil...
> Réponse :	500 Sorry, no server available to handle request on **10.255.0.17**
I already try in active or passive mode...

**Netstat output :** 
> tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      - 

**stack file :**
> version: "3"
> services:
>   proftp:
> image: test-ftp:latest
>     ports:
>       - "20:20"
>       - "21:21"
>       - "60000-60010:60000-60010"
>     volumes:
>       - "data:/ftpdata"
> volumes:
>   data:

**proftpd.conf file:**
> ServerName "ftp server"
> DefaultRoot ~
> UseIPv6 off
> User ftp
> Group users
> RequireValidShell off
> AllowOverwrite on
> AuthUserFile /etc/proftpd/ftpd.passwd
> MaxClients 50
> CreateHome on 700 uid 105 gid 100
> MasqueradeAddress srv1.test.org
> PassivePorts 60000 60010
> IdentLookups off
> UseReverseDNS off
> TimeoutIdle 900
> TimeoutNoTransfer 900
> TimesGMT Off

Thanks for help, I really need it for my work !

-Olivier.

**Comment by AndrewVos** [comment]
I haven't worked on this years so sadly can't be any help.

**Comment by osfrance** [comment]
Ok thanks for help, you know someone can helping me ?

**Comment by bingen** [comment]
I have the same problem with both `vsftpd` and `proftpd` in swarm mode. I think the problem is the IP address translation docker swarm does, as I see with `tcpdump`:
```
19:34:53.044711 IP 10.255.0.3.46096 > 10.255.0.4.21: Flags [P.], seq 36:63, ack 97, win 229, options [nop,nop,TS val 3290369629 ecr 129178698], length 27: FTP: PORT 192,168,1,137,152,71
19:34:53.045589 IP 10.255.0.4.21 > 10.255.0.3.46096: Flags [P.], seq 97:124, ack 63, win 219, options [nop,nop,TS val 129179616 ecr 3290369629], length 27: FTP: 500 Illegal PORT command.
```
As you can see the packet origin address (`10.255.0.3`) differs from the real origin one (`192.168.1.137`) which is advertised by FTP.

**Comment by cmizzi** [comment]
You have to configure `proftpd` with `MasqueradeAddress` directive (http://proftpd.org/docs/directives/linked/config_ref_MasqueradeAddress.html).

**Comment by osfrance** [comment]
Yes, I confirm Proftpd in Docker Warm work with `MasqueradeAddress` directive
